config/routes.rb
ProductsApp::Application.routes.draw do

  resources :product_solds

  resources :products do
    get 'sell', :on => :member
  end

  match '/home', to: 'static_pages#home'  

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

  root :to => "products#index" #index me muestra la def index de home controller

end

app/models/product.rb
class Product < ActiveRecord::Base

  attr_accessible :description, :name, :price, :image
  mount_uploader :image, ImageUploader
  validates :description, :presence => true
  validates :name, :presence => true
  validates :price, :presence => true, :numericality => true

  has_many :product_sold

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

  #crea un ProductSold
  def sell
    productSold = ProductSold.new

    productSold.price       = self.price
    productSold.product_id  = self.id

    productSold.save
  end

end

app/models/product_sold.rb
class ProductSold < ActiveRecord::Base

  attr_accessible :price, :product_id
  validates :price, :presence => true, :numericality => true

  belongs_to :product

  def self.search(params)
    if search
      where(:created_at => params[:date_from]..params[:date_to])
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/product_solds_controller.rb
class ProductSoldsController < ApplicationController
  # GET /product_solds
  # GET /product_solds.json
  def index
  #  @product_solds = ProductSold.paginate(page: params[:page]).search(params)
     @product_solds = ProductSold.paginate(page: params[:page])
  end

  # GET /product_solds/1
  # GET /product_solds/1.json
  def show
    @product_sold = ProductSold.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_sold }
    end
  end

  # GET /product_solds/new
  # GET /product_solds/new.json
  def new
    print params
    @product_sold = ProductSold.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_sold }
    end
  end

  # GET /product_solds/1/edit
  def edit
    @product_sold = ProductSold.find(params[:id])
  end

  # POST /product_solds
  # POST /product_solds.json
  def create
    @product_sold = ProductSold.new(params[:product_sold])

    respond_to do |format|
      if @product_sold.save
        format.html { redirect_to @product_sold, notice: 'Product sold was successfully created.' }
        format.json { render json: @product_sold, status: :created, location: @product_sold }
      else
        format.html { render action: "new" }
        format.json { render json: @product_sold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_solds/1
  # PUT /product_solds/1.json
  def update
    @product_sold = ProductSold.find(params[:id])

    respond_to do |format|
      if @product_sold.update_attributes(params[:product_sold])
        format.html { redirect_to @product_sold, notice: 'Product sold was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_sold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_solds/1
  # DELETE /product_solds/1.json
  def destroy
    @product_sold = ProductSold.find(params[:id])
    @product_sold.destroy

    respond_to do |format|
      format.html { redirect_to product_solds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page]).search(params[:search])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  # vende al producto este. la logica esta en el modelo
  def sell
    @product = Product.find(params[:id])

    if @product.sell
      redirect_to products_path, notice: 'Product was successfully sold.' 
    else
      render action: "new" 
    end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)

    base_title = "Sistema de administracion"

    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end

  end

end

app/helpers/product_solds_helper.rb
module ProductSoldsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Products", root_path %></li>
          <li><%= link_to "Products Sold", product_solds_path %></li>
          <li><%= link_to "Help", help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_menu.html.erb
hola menu

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <% flash.each do |key, value| %>
        <!-- <div class="alert alert-<%= key %>"><%= value %></div> -->
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/product_solds/_form.html.erb
<%= form_for @product_sold, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :product_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :product_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                product_solds_path, :class => 'btn' %>
  </div>
<% end %>

app/views/product_solds/edit.html.erb
<%- model_class = ProductSold -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/product_solds/index.html.erb
<%- model_class = ProductSold -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= form_tag product_solds_path, :method => 'get', :class => 'form-search' do %>
  <p>
    <%= text_field_tag :date_from, params[:date_from], 
                        'data-behaviour' => 'datepicker',
                        :class => 'datepicker input-medium', 
                        'placeholder' => 'Date from'%>
    <%= text_field_tag :date_to, params[:date_to], 
                        'data-behaviour' => 'datepicker',
                        :class => 'datepicker input-medium', 
                        'placeholder' => 'Date to'%>
    <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary' %>
  </p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @product_solds.each do |product_sold| %>
      <tr>
        <td><%= product_sold.product.name %></td>
        <td><%= product_sold.price %></td>
        <td><%=l product_sold.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/product_solds/new.html.erb
<%- model_class = ProductSold -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/product_solds/show.html.erb
<%- model_class = ProductSold -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @product_sold.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product_sold.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              product_solds_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_sold_path(@product_sold), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_sold_path(@product_sold),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/products/_fields.html.erb
<%= #render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :price %>
<%= f.text_field :price %>

<%= f.label :image %>
<%= f.text_field :image %>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
      <% unless @product.image_url.to_s.empty? %>
        <%= image_tag @product.image_url(:thumb).to_s %>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/_product.html.erb
<!-- #no se usa -->
<li>
  <%= product.image %>
  <%= product.name %>
  <%= product.description %>
  <%= product.price %>
  <%= link_to 'Show', product %>
  <%= link_to 'Edit', edit_product_path(product) %>
  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
</li>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<div class="search-form">
  <%= form_tag products_path, :method => 'get', :class => 'form-search' do %>
    <p>
      <%= text_field_tag :search, params[:search], :class => 'input-large' %>
      <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary' %>

    </p>

  <% end %>

</div>

<div class="new_button">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_product_path,
              :class => 'btn btn-primary' %>
</div>

<% @products.each do |product| %>
  <div class="product">
    <%= link_to (image_tag product.image_url(:thumb).to_s , :alt =>product.name),
                  :controller => "products",
                  :action => "sell",
                  :id => product 
    %>
    <p>$<%= product.price %>, <%= product.name %></p>    
  </div>
<% end %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @product.image_url(:thumb).to_s %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>